linters-settings:
  wrapcheck:
    # An error returned from these packages must be wrapped
    ignorePackageGlobs:
      - encoding/*
      - github.com/contactkeval/option-replay/*
    ignoreInterfaceCaseless: true

  revive:
    # High-level idiomatic Go rules
    rules:
      - name: exported
      - name: indent-error-flow
      - name: receiver-naming

  govet:
    check-shadowing: true
    enable-all: true

linters:
  disable-all: true
  enable:
    - wrapcheck    # Forces error wrapping
    - revive       # Replacement for golint
    - staticcheck  # Advanced static analysis
    - govet        # Standard Go vet tool
    - errcheck     # Checks for unchecked errors
    - goconst      # Finds repeated strings that should be constants
    - gosimple     # Suggests code simplifications

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false # Usually better to focus on source code first